apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: greet-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: greet
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
